-- =============================================================================
-- テスト用ユーザー・権限・ディレクトリ作成
-- SYSTEM ユーザーで実行
-- =============================================================================

-- テスト用ユーザー1
BEGIN
    EXECUTE IMMEDIATE 'DROP USER ODV_TEST CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE USER ODV_TEST IDENTIFIED BY odv_test
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO ODV_TEST;
GRANT CREATE TABLE TO ODV_TEST;
GRANT CREATE SEQUENCE TO ODV_TEST;
GRANT CREATE VIEW TO ODV_TEST;
GRANT CREATE TYPE TO ODV_TEST;
GRANT CREATE PROCEDURE TO ODV_TEST;
GRANT UNLIMITED TABLESPACE TO ODV_TEST;

-- テスト用ユーザー2 (複数スキーマテスト)
BEGIN
    EXECUTE IMMEDIATE 'DROP USER ODV_TEST2 CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE USER ODV_TEST2 IDENTIFIED BY odv_test2
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON USERS;

GRANT CONNECT, RESOURCE TO ODV_TEST2;
GRANT CREATE TABLE TO ODV_TEST2;
GRANT UNLIMITED TABLESPACE TO ODV_TEST2;

-- EXPDP 用ディレクトリ
BEGIN
    EXECUTE IMMEDIATE 'DROP DIRECTORY dump_dir';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE DIRECTORY dump_dir AS '/opt/oracle/dump';
GRANT READ, WRITE ON DIRECTORY dump_dir TO ODV_TEST;
GRANT READ, WRITE ON DIRECTORY dump_dir TO ODV_TEST2;

-- EXP_FULL_DATABASE / IMP_FULL_DATABASE 権限 (FULL エクスポート用)
GRANT EXP_FULL_DATABASE TO ODV_TEST;

EXIT;
