-- =============================================================================
-- 高度なシナリオ (パーティション / IOT / ビュー / 索引 / 制約)
-- ODV_TEST ユーザーで実行
-- =============================================================================

-- パーティションテーブル (レンジ)
CREATE TABLE T_PARTITIONED_RANGE (
    ID              NUMBER(10)      NOT NULL,
    SALE_DATE       DATE            NOT NULL,
    AMOUNT          NUMBER(12, 2),
    REGION          VARCHAR2(50),
    CONSTRAINT PK_PART_RANGE PRIMARY KEY (ID, SALE_DATE)
)
PARTITION BY RANGE (SALE_DATE) (
    PARTITION P_2024 VALUES LESS THAN (TO_DATE('2025-01-01', 'YYYY-MM-DD')),
    PARTITION P_2025 VALUES LESS THAN (TO_DATE('2026-01-01', 'YYYY-MM-DD')),
    PARTITION P_2026 VALUES LESS THAN (TO_DATE('2027-01-01', 'YYYY-MM-DD')),
    PARTITION P_MAX  VALUES LESS THAN (MAXVALUE)
);

INSERT INTO T_PARTITIONED_RANGE VALUES (1, TO_DATE('2024-06-15', 'YYYY-MM-DD'), 1500.00, 'Tokyo');
INSERT INTO T_PARTITIONED_RANGE VALUES (2, TO_DATE('2025-03-20', 'YYYY-MM-DD'), 2300.50, 'Osaka');
INSERT INTO T_PARTITIONED_RANGE VALUES (3, TO_DATE('2026-01-10', 'YYYY-MM-DD'), 4200.00, 'Nagoya');
INSERT INTO T_PARTITIONED_RANGE VALUES (4, TO_DATE('2026-03-08', 'YYYY-MM-DD'), 800.75, 'Fukuoka');

COMMIT;

-- パーティションテーブル (ハッシュ)
CREATE TABLE T_PARTITIONED_HASH (
    ID              NUMBER(10)      NOT NULL,
    COL_NAME        VARCHAR2(200),
    COL_VALUE       NUMBER,
    CONSTRAINT PK_PART_HASH PRIMARY KEY (ID)
)
PARTITION BY HASH (ID) PARTITIONS 4;

BEGIN
    FOR i IN 1..100 LOOP
        INSERT INTO T_PARTITIONED_HASH VALUES (i, 'Hash partition record ' || i, i * 10);
    END LOOP;
    COMMIT;
END;
/

-- パーティションテーブル (リスト)
CREATE TABLE T_PARTITIONED_LIST (
    ID              NUMBER(10)      NOT NULL,
    COUNTRY         VARCHAR2(50)    NOT NULL,
    COL_NAME        VARCHAR2(200),
    CONSTRAINT PK_PART_LIST PRIMARY KEY (ID)
)
PARTITION BY LIST (COUNTRY) (
    PARTITION P_JP VALUES ('Japan'),
    PARTITION P_US VALUES ('USA'),
    PARTITION P_EU VALUES ('Germany', 'France', 'UK'),
    PARTITION P_OTHER VALUES (DEFAULT)
);

INSERT INTO T_PARTITIONED_LIST VALUES (1, 'Japan', 'Tokyo Office');
INSERT INTO T_PARTITIONED_LIST VALUES (2, 'USA', 'New York Office');
INSERT INTO T_PARTITIONED_LIST VALUES (3, 'Germany', 'Berlin Office');
INSERT INTO T_PARTITIONED_LIST VALUES (4, 'Australia', 'Sydney Office');

COMMIT;

-- 索引構成表 (IOT)
CREATE TABLE T_IOT (
    ID              NUMBER(10)      NOT NULL,
    COL_KEY         VARCHAR2(50)    NOT NULL,
    COL_VALUE       VARCHAR2(200),
    CONSTRAINT PK_IOT PRIMARY KEY (ID)
) ORGANIZATION INDEX;

INSERT INTO T_IOT VALUES (1, 'key_alpha', 'Value Alpha');
INSERT INTO T_IOT VALUES (2, 'key_beta', 'Value Beta');
INSERT INTO T_IOT VALUES (3, 'key_gamma', 'Value Gamma');
INSERT INTO T_IOT VALUES (10, 'key_omega', 'Value Omega');

COMMIT;

-- クラスタテーブル
BEGIN
    EXECUTE IMMEDIATE 'DROP CLUSTER CL_TEST INCLUDING TABLES';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE CLUSTER CL_TEST (DEPT_ID NUMBER(10));
CREATE INDEX IDX_CL_TEST ON CLUSTER CL_TEST;

CREATE TABLE T_CLUSTER_DEPT (
    DEPT_ID         NUMBER(10)      NOT NULL,
    DEPT_NAME       VARCHAR2(100),
    CONSTRAINT PK_CL_DEPT PRIMARY KEY (DEPT_ID)
) CLUSTER CL_TEST (DEPT_ID);

CREATE TABLE T_CLUSTER_EMP (
    EMP_ID          NUMBER(10)      NOT NULL,
    DEPT_ID         NUMBER(10)      NOT NULL,
    EMP_NAME        VARCHAR2(100),
    CONSTRAINT PK_CL_EMP PRIMARY KEY (EMP_ID),
    CONSTRAINT FK_CL_EMP_DEPT FOREIGN KEY (DEPT_ID) REFERENCES T_CLUSTER_DEPT(DEPT_ID)
) CLUSTER CL_TEST (DEPT_ID);

INSERT INTO T_CLUSTER_DEPT VALUES (10, 'Engineering');
INSERT INTO T_CLUSTER_DEPT VALUES (20, 'Sales');
INSERT INTO T_CLUSTER_EMP VALUES (1, 10, 'Alice');
INSERT INTO T_CLUSTER_EMP VALUES (2, 10, 'Bob');
INSERT INTO T_CLUSTER_EMP VALUES (3, 20, 'Charlie');

COMMIT;

-- ビュー
CREATE VIEW V_BASIC_SUMMARY AS
    SELECT ID, COL_VARCHAR2, COL_CHAR
    FROM T_BASIC_TYPES
    WHERE ID <= 3;

-- マテリアライズドビュー
CREATE MATERIALIZED VIEW MV_LARGE_SUMMARY
    BUILD IMMEDIATE
    REFRESH COMPLETE ON DEMAND
AS
    SELECT COL_NAME, COUNT(*) AS CNT, SUM(COL_VALUE) AS TOTAL
    FROM T_LARGE_TABLE
    GROUP BY COL_NAME;

-- シーケンス
CREATE SEQUENCE SEQ_TEST START WITH 1 INCREMENT BY 1 MAXVALUE 999999;

-- 複合一意制約
CREATE TABLE T_CONSTRAINTS (
    ID              NUMBER(10)      NOT NULL,
    COL_A           VARCHAR2(50)    NOT NULL,
    COL_B           VARCHAR2(50)    NOT NULL,
    COL_C           VARCHAR2(50),
    COL_CHECK       NUMBER          CHECK (COL_CHECK >= 0 AND COL_CHECK <= 100),
    CONSTRAINT PK_CONSTRAINTS PRIMARY KEY (ID),
    CONSTRAINT UQ_CONSTRAINTS UNIQUE (COL_A, COL_B)
);

INSERT INTO T_CONSTRAINTS VALUES (1, 'A1', 'B1', 'C1', 50);
INSERT INTO T_CONSTRAINTS VALUES (2, 'A2', 'B2', 'C2', 100);
INSERT INTO T_CONSTRAINTS VALUES (3, 'A3', 'B3', NULL, 0);

COMMIT;

-- 外部キー参照テーブル
CREATE TABLE T_FK_PARENT (
    PARENT_ID       NUMBER(10)      NOT NULL,
    PARENT_NAME     VARCHAR2(100),
    CONSTRAINT PK_FK_PARENT PRIMARY KEY (PARENT_ID)
);

CREATE TABLE T_FK_CHILD (
    CHILD_ID        NUMBER(10)      NOT NULL,
    PARENT_ID       NUMBER(10)      NOT NULL,
    CHILD_NAME      VARCHAR2(100),
    CONSTRAINT PK_FK_CHILD PRIMARY KEY (CHILD_ID),
    CONSTRAINT FK_CHILD_PARENT FOREIGN KEY (PARENT_ID) REFERENCES T_FK_PARENT(PARENT_ID)
);

INSERT INTO T_FK_PARENT VALUES (1, 'Parent 1');
INSERT INTO T_FK_PARENT VALUES (2, 'Parent 2');
INSERT INTO T_FK_CHILD VALUES (1, 1, 'Child 1-1');
INSERT INTO T_FK_CHILD VALUES (2, 1, 'Child 1-2');
INSERT INTO T_FK_CHILD VALUES (3, 2, 'Child 2-1');

COMMIT;

-- 各種インデックス
CREATE INDEX IDX_LARGE_NAME ON T_LARGE_TABLE (COL_NAME);
CREATE INDEX IDX_LARGE_DATE ON T_LARGE_TABLE (COL_DATE);
CREATE BITMAP INDEX IDX_PART_REGION ON T_PARTITIONED_RANGE (REGION) LOCAL;

-- 仮想列 (Virtual Column)
CREATE TABLE T_VIRTUAL_COLUMN (
    ID              NUMBER(10)      NOT NULL,
    PRICE           NUMBER(10, 2),
    QUANTITY        NUMBER(10),
    TOTAL           NUMBER(12, 2) GENERATED ALWAYS AS (PRICE * QUANTITY) VIRTUAL,
    CONSTRAINT PK_VIRTUAL_COL PRIMARY KEY (ID)
);

INSERT INTO T_VIRTUAL_COLUMN (ID, PRICE, QUANTITY) VALUES (1, 100.50, 3);
INSERT INTO T_VIRTUAL_COLUMN (ID, PRICE, QUANTITY) VALUES (2, 250.00, 10);
INSERT INTO T_VIRTUAL_COLUMN (ID, PRICE, QUANTITY) VALUES (3, 0, 0);

COMMIT;

-- DEFAULT 値テスト
CREATE TABLE T_DEFAULTS (
    ID              NUMBER(10) GENERATED ALWAYS AS IDENTITY,
    COL_DEF_STR     VARCHAR2(100) DEFAULT 'DEFAULT_VALUE',
    COL_DEF_NUM     NUMBER DEFAULT 0,
    COL_DEF_DATE    DATE DEFAULT SYSDATE,
    COL_DEF_NULL    VARCHAR2(100) DEFAULT NULL,
    COL_NO_DEF      VARCHAR2(100),
    CONSTRAINT PK_DEFAULTS PRIMARY KEY (ID)
);

INSERT INTO T_DEFAULTS (COL_NO_DEF) VALUES ('Only this column set');
INSERT INTO T_DEFAULTS (COL_DEF_STR, COL_DEF_NUM, COL_NO_DEF) VALUES ('Custom', 999, 'Custom values');
INSERT INTO T_DEFAULTS (COL_DEF_STR, COL_DEF_NUM, COL_DEF_DATE, COL_DEF_NULL, COL_NO_DEF)
    VALUES ('Explicit', 42, TO_DATE('2020-01-01', 'YYYY-MM-DD'), 'not null', 'All set');

COMMIT;

EXIT;
